site_name: '小荔枝的百科'
site_url: 'https://szu.wiki/'

repo_name: 'libopenszu/wiki'
repo_url: 'https://github.com/libopenszu/wiki'

copyright: '除非另有声明，本网站内容采用知识共享署名-非商业性使用-相同方式共享授权。'

nav:
  - 校区:
    - 粤海校区:
      - 基本信息: university/yuehai/index/index.md
#    - 建筑:
#      - 宿舍:
#
    - 沧海校区:
      - 基本信息: university/canghai/index/index.md
    - 丽湖校区:
      - 基本信息: university/lihu/index/index.md
    - 罗湖校区:
      - 基本信息: university/luohu/index/index.md
    - 校区及建筑道路等命名变更: university/buildings_and_roads_renaming/index.md
  - 通用:
    - 微信公众号: universal/wechat_official_account/index.md
    - 校历:
      - 2020-2021学年第一学期: universal/calendar/2020-2021-1/index.md
    - 校务信箱: universal/mailbox/index.md
    - 校园卡: universal/school_card/index.md
    - 校园码: universal/school_qrcode/index.md
    - 校园网络:
      - 教学区: universal/network/teaching_area/index.md
      - 宿舍区: universal/network/dormitory_area/index.md
      - 校外访问: universal/network/vpn/index.md
    - 校园邮箱:
      - 教师电子邮箱: universal/email/teacher/index.md
      - 学生电子邮箱: universal/email/student/index.md
    - 校长午餐会: universal/luncheon/index.md
    - 运动会:
      - 彩色跑: universal/sports_meeting/color_run/index.md
  - 学习:
    - 绩点: learning/gpa/index.md
    - 奖学金: learning/scholarship/index.md
    - 培养方案:
      - 2020级:
        - 计算机科学与技术: learning/plans/2020/computer_science_and_technology/index.md
    - 选课: learning/course_selecting/index.md
  - 生活:
    - 健身房: living/gym/index.md
    - 社团:
      - 首页: living/associations/index/index.md
      - 深圳大学荔进社: living/associations/2001/index.md
      - 深圳大学信息网络安全协会: living/associations/3001/index.md
      - 深圳大学吉他社: living/associations/10021/index.md
      - 深圳大学RobotPilots机器人俱乐部: living/associations/15001/index.md
      - 腾讯创新俱乐部: living/associations/18002/index.md
      - 深圳大学魔方协会: living/associations/mofangxiehui/index.md
    - 水电费: living/utility_bill/index.md
    - 团学组织:
      - 首页: living/tuanxue/index/index.md
    - 校友会/同乡会:
      - 福建分会（筹）: living/alumni_associations/fujian/index.md
      - 广东省:
        - 揭阳: living/alumni_associations/guangdong/jieyang/index.md
        - 汕头: living/alumni_associations/guangdong/shantou/index.md
      - 江西: living/alumni_associations/jiangxi/index.md
  - 新生特供:
    - 首页: for_freshman/index/index.md
    - 深大盒子:
      - 简介: for_freshman/box/index/index.md
      - 2019年: for_freshman/box/2019/index.md
      - 2018年: for_freshman/box/2018/index.md
      - 2017年: for_freshman/box/2017/index.md
    - 必备物品: for_freshman/essential_items/index.md
    - 快递收寄: for_freshman/express_delivery/index.md
    - 防盗和反欺诈: for_freshman/anti-theft-fraud/index.md
  - 关于:
    - 首页: index.md
    - 如何贡献: edit/index.md
  - 紧急情况:
    - 生命救援或紧急情况: emergency/index/index.md
    - 自动体外心脏除颤器（AED）分布: emergency/aed/index.md

theme:
  features:
    - tabs
#    - instant
  language: 'zh'
  name: 'material'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/libopenszu'
    - icon: 'fontawesome/brands/telegram'
      link: 'https://t.me/szu_group'

extra_css:
  - css/extra.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.bootcdn.net/ajax/libs/mathjax/3.0.5/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
